### ISSUE TITLE
Tweet refiltering

### ISSUE THREAD

**Issue by joe4dev** [gmazlami/adv_se_project#13]
* Can we rematch all the tweets we get from the streaming API to our filtered phrases?
* Data to consider
  * tweettext
  * username
  * expanded_urls
  * ... ???

**Comment by Clabfabs** [comment]
Hey guys,
I pushed some code to refilter the received tweets. According to the [Twitter API] (https://dev.twitter.com/streaming/overview/request-parameters#track), the following data is considered:

* tweet.text
* tweet.entities
 * urls
   * expanded_url
    * display_url
 * media
   * expanded_url
    * display_url
 * hashtags
   * text
 * user_mentions
    * screen_name

The code I pushed is a little different than the previous version, especially because I had troubles with the "mongodb" package (I've used it before, but I couldn't make it work the way I wanted to). That's why I use mongoose again... Hope that's fine for you. I also changed the logic of the database because we now have refiltering: After a match, it checks if the phrase is already in the database - if yes, it updates the sentiment value; if no, it creates a document for the phrase and sets an initial sentiment value. Like this, in theory, we have one document per phrase we're observing. However, in practice, it seems to create duplicates, didn't figure out why yet. If we can somehow use this code, we might have another task for the workers: aggregate duplicates.

One last thing: The actual task, to rematch all the tweet, is not completed yet. I have to figure out a good regular expression that covers all the stuff that's stated in the API (Link above). Right now, it still "searches" for the phrase in all the mentioned attributes.

Good night!
