### ISSUE TITLE
Sentiment Analysis 

### ISSUE THREAD

**Issue by dschoeni** [gmazlami/adv_se_project#9]
Can we use a really complex library that slows stuff down so we can demonstrate the scaling feature more easily.

**Comment by Clabfabs** [comment]
I created a simple node app to first fill the database and then to compare the "sentiment" and Sentimental" library with these tweets. It turns out that they don't really perform much differently. But one thing I found out is, that the "sentiment" library uses some kind of error handler, if the corresponding tweet text is not readable / not there. That's why this library analyzes slightly less tweets, but it doesn't need a manual validation.
I included it anyway, otherwise the "Sentimental" library failed.
Here are the values (sentiment | Sentimental)
* Total number of tweets: 39682
* time passed (ms): 5856 | 6118
* tweets analyzed: 36617 | 37255
* average sentiment score: 0.7758145123849604 | 0.8681250838813583

I'll leave this one open, maybe I'll fill my database a little more and get more interesting results.
